[feat] 로그인 페이지 기능 구현, yarn 설정 변경
gacheon-sw-academy-2023/Frontier-Client pull request #20
Opened 2023-01-19 00:23 UTC by JeongGyu98

## PR Checklist
아래 요구사항을 만족하는지 체크:

- [ ] 작성한 코드에 대한 테스트 코드 작성 (기능 추가 / 버그 개선)
- [ ] 작성한 코드 문서화 (기능 추가 / 버그 개선)

## PR Type
해당 PR이 포함하는 내용 체크:

- [x] 패키지
  - [ ] 패키지 추가
  - [x] 패키지 설정 변경
- [ ] CI
  - [ ] CI 구성 추가
  - [ ] CI 설정 변경
- [ ] 문서화
  - [ ] 신규 문서 추가
  - [ ] 기존 문서 변경
- [x] 신규 기능 추가
- [ ] 버그 수정
- [x] 코드 개선
  - [ ] 성능 개선
  - [x] UI 개선
  - [ ] 성능에 영향을 끼치지 않는 수정
- [ ] 테스트
  - [ ] 테스트 코드 추가
  - [ ] 기존 테스트 코드 변경
- [ ] 커밋 되돌리기
- [ ] 기타

## 해당 PR에 대한 설명

로그인 페이지 기능 구현, UI 수정 - 로그인 api 작성 

Yarn 설정 파일 변경 

+ 구글 로그인 작업 예정 

## 스크린샷
<img width="1242" alt="스크린샷 2023-01-19 오전 9 21 53" src="https://user-images.githubusercontent.com/76028541/213326504-51509fca-d667-4ddc-92a8-84701278b231.png">

## 기타 정보

2023-01-19 00:29 UTC, vbnm134678 commented on src/pages/Login/index.tsx
> +            <img className=" w-60" src={Logo} alt="" />
tailwindcss를 styled-componetns로 추후 바꾸셔야 될 것 같습니다!

2023-01-19 00:31 UTC, vbnm134678 approved these changes
피드백 반영해서 Router 관련 변경하신 것 확인 했습니다!
로그인 이쁘게 잘 된 것 같네요!

2023-01-19 00:33 UTC, JeongGyu98 commented on src/pages/Login/index.tsx
> +            <img className=" w-60" src={Logo} alt="" />
확인했습니다. 수정할께요

2023-01-19 01:39 UTC, whquddnr97 requested changes
추가적으로 발생한 버그는 별도로 이슈 만들어서 올리겠습니다!

2023-01-19 01:39 UTC, whquddnr97 commented on src/components/LoginForm/index.tsx
> +            </p>
이메일, 비밀번호 입력할때 아래에 있는 모든 버튼들이 다시 렌더링 되는 것 같은데 확인부탁드려용

2023-01-19 01:39 UTC, whquddnr97 commented on src/tests/mocks/handlers/loginHandler.ts
> +    }),
테스트용 코드 삭제 부탁드려용

2023-01-19 01:39 UTC, whquddnr97 commented on src/components/LoginForm/index.tsx
> +    const [userpassword, setUserPassword] = useState("");
변수명 userEmail, userPassword, setUserEmail 이렇게 통일하는게 좋을 것 같아용

2023-01-19 01:39 UTC, whquddnr97 commented on src/components/LoginForm/index.tsx
> +    const [isLoading, setIsLoading] = useState(false);
로딩 상태일 때 보여지는 UI가 없는 것 같아요

2023-01-19 02:12 UTC, JeongGyu98 commented on src/tests/mocks/handlers/loginHandler.ts
> +    }),
테스트용 코드 삭제 완료했습니다!

2023-01-19 02:15 UTC, JeongGyu98 commented on src/components/LoginForm/index.tsx
> +            </p>
그런가요? 저는 확인이 안되는 것 같은데 다시 한번보고 코멘트 하겠습니다.

2023-01-19 02:16 UTC, JeongGyu98 commented on src/components/LoginForm/index.tsx
> +    const [userpassword, setUserPassword] = useState("");
넵 확인이요

2023-01-19 02:17 UTC, JeongGyu98 commented on src/components/LoginForm/index.tsx
> +    const [isLoading, setIsLoading] = useState(false);
버튼 자체를 component로 분리해서 isLoading 값을 props로 넘길 계획입니다.
추후에 수정예정입니다!

2023-01-21 08:34 UTC, whquddnr97 approved these changes

2023-01-21 23:56 UTC, merged