[design] HomePage - navbar, sidebar, content 디자인
gacheon-sw-academy-2023/Frontier-Client pull request #23
Opened 2023-01-19 02:58 UTC by vbnm134678

## PR Checklist
아래 요구사항을 만족하는지 체크:

- [ ] 작성한 코드에 대한 테스트 코드 작성 (기능 추가 / 버그 개선)
- [ ] 작성한 코드 문서화 (기능 추가 / 버그 개선)

## PR Type
해당 PR이 포함하는 내용 체크:

- [ ] 패키지
  - [ ] 패키지 추가
  - [ ] 패키지 설정 변경
- [ ] CI
  - [ ] CI 구성 추가
  - [ ] CI 설정 변경
- [ ] 문서화
  - [ ] 신규 문서 추가
  - [ ] 기존 문서 변경
- [ ] 신규 기능 추가
- [ ] 버그 수정
- [x] 코드 개선
  - [ ] 성능 개선
  - [x] UI 개선
  - [x] 성능에 영향을 끼치지 않는 수정
- [ ] 테스트
  - [ ] 테스트 코드 추가
  - [ ] 기존 테스트 코드 변경
- [ ] 커밋 되돌리기
- [ ] 기타

## 해당 PR에 대한 설명
HomePage UI 디자

## 스크린샷
![image](https://user-images.githubusercontent.com/76089508/213345071-77acc0be-9f0a-49e0-b5db-ec9d91892ed0.png)

## 기타 정보

2023-01-19 03:01 UTC, whquddnr97 requested changes

2023-01-19 04:36 UTC, vbnm134678 commented on .vscode/settings.json
> +}
등록 설정 완료 했습니다.

2023-01-19 04:36 UTC, vbnm134678 commented on src/components/Navbar/index.tsx
> +        console.log(searching);
삭제 완료했습니당

2023-01-20 07:17 UTC, JeongGyu98 approved these changes
확인 완료했습니다.

2023-01-20 07:17 UTC, JeongGyu98 commented on src/components/Navbar/index.tsx
> +                    <button type="button" className="head_user">
버튼 컴포넌트 만드는게 우선적으로 필요할 것 같네요

2023-01-20 10:35 UTC, vbnm134678 commented on src/components/Navbar/index.tsx
> +                    <button type="button" className="head_user">
만들어서 component에 추가하도록 하겠습니다!

2023-01-21 08:34 UTC, whquddnr97 approved these changes

2023-01-21 23:56 UTC, merged