feat: 회원가입 API 작성, 유효성 검사 구현
gacheon-sw-academy-2023/Frontier-Client pull request #25
Opened 2023-01-22 04:52 UTC by JeongGyu98

## PR Checklist
아래 요구사항을 만족하는지 체크:

- [ ] 작성한 코드에 대한 테스트 코드 작성 (기능 추가 / 버그 개선)
- [ ] 작성한 코드 문서화 (기능 추가 / 버그 개선)

## PR Type
해당 PR이 포함하는 내용 체크:

- [ ] 패키지
  - [ ] 패키지 추가
  - [ ] 패키지 설정 변경
- [ ] CI
  - [ ] CI 구성 추가
  - [ ] CI 설정 변경
- [ ] 문서화
  - [ ] 신규 문서 추가
  - [ ] 기존 문서 변경
- [x] 신규 기능 추가
- [ ] 버그 수정
- [x] 코드 개선
  - [ ] 성능 개선
  - [x] UI 개선
  - [ ] 성능에 영향을 끼치지 않는 수정
- [ ] 테스트
  - [ ] 테스트 코드 추가
  - [ ] 기존 테스트 코드 변경
- [ ] 커밋 되돌리기
- [ ] 기타

## 해당 PR에 대한 설명

회원가입 API 작성, 테스트 코드 삭제 

회원가입 페이지 UI 수정 

## 스크린샷

## 기타 정보

2023-01-22 12:43 UTC, whquddnr97 requested changes
회원가입 API 작성 및 유효성 검사 구현 확인했습니당
회원가입 API 부분은 로그인 API 부분이랑 추후에 분리해도 될 것 같아용

2023-01-22 12:43 UTC, whquddnr97 commented on src/components/RegisterForm/index.tsx
> +                console.log("회원가입 실패");
console.log 확인 부탁드려용

2023-01-23 05:03 UTC, JeongGyu98 commented on src/components/RegisterForm/index.tsx
> +                console.log("회원가입 실패");
수정 완료했습니다.

2023-01-24 08:44 UTC, vbnm134678 approved these changes
회원가입 api와 유효성 검사관련 코드 확인 했습니다.

2023-01-25 07:14 UTC, merged