[feat] 리스트 드래그 앤 드랍 버그 수정, 리스트 수정 기능 추가
gacheon-sw-academy-2023/Frontier-Client pull request #49
Opened 2023-02-03 11:03 UTC by JeongGyu98

## PR Checklist
아래 요구사항을 만족하는지 체크:

- [ ] 작성한 코드에 대한 테스트 코드 작성 (기능 추가 / 버그 개선)
- [ ] 작성한 코드 문서화 (기능 추가 / 버그 개선)

## PR Type
해당 PR이 포함하는 내용 체크:

- [ ] 패키지
  - [ ] 패키지 추가
  - [ ] 패키지 설정 변경
- [ ] CI
  - [ ] CI 구성 추가
  - [ ] CI 설정 변경
- [ ] 문서화
  - [ ] 신규 문서 추가
  - [ ] 기존 문서 변경
- [ ] 신규 기능 추가
- [x] 버그 수정
- [x] 코드 개선
  - [x] 성능 개선
  - [x] UI 개선
  - [ ] 성능에 영향을 끼치지 않는 수정
- [ ] 테스트
  - [ ] 테스트 코드 추가
  - [ ] 기존 테스트 코드 변경
- [ ] 커밋 되돌리기
- [ ] 기타

## 해당 PR에 대한 설명
리스트 드래그 앤 드랍 버그 수정. 
리스트 이름 수정 기능 추가. 
List editor 컴포넌트 추가 .

## 스크린
![스크린샷 2023-02-03 오후 8 00 28](https://user-images.githubusercontent.com/76028541/216587205-c22a789c-4bdb-4087-a93c-0d5cb98e2f82.png)
샷

## 기타 정보

2023-02-03 13:07 UTC, vbnm134678 approved these changes
기능추가랑 버그 수정 수고하셨습니다!

2023-02-05 16:34 UTC, whquddnr97 requested changes

2023-02-05 16:34 UTC, whquddnr97 commented on src/components/Board/List/index.tsx
> +                        onMouseLeave={() => setIsHover(false)}
이부분 css hover 대신에 따로 상태 저장하신 이유가 있을까용?

2023-02-05 19:37 UTC, whquddnr97 approved these changes
리스트 정상 작동 확인했습니다!

2023-02-05 19:37 UTC, merged