[개선] 홈화면 UI 개선
gacheon-sw-academy-2023/Frontier-Client pull request #59
Opened 2023-02-08 11:00 UTC by vbnm134678

## PR Checklist
아래 요구사항을 만족하는지 체크:

- [ ] 작성한 코드에 대한 테스트 코드 작성 (기능 추가 / 버그 개선)
- [ ] 작성한 코드 문서화 (기능 추가 / 버그 개선)

## PR Type
해당 PR이 포함하는 내용 체크:

- [ ] 패키지
  - [ ] 패키지 추가
  - [ ] 패키지 설정 변경
- [ ] CI
  - [ ] CI 구성 추가
  - [ ] CI 설정 변경
- [ ] 문서화
  - [ ] 신규 문서 추가
  - [ ] 기존 문서 변경
- [x] 신규 기능 추가
- [ ] 버그 수정
- [x] 코드 개선
  - [x] 성능 개선
  - [x] UI 개선
  - [x] 성능에 영향을 끼치지 않는 수정
- [ ] 테스트
  - [ ] 테스트 코드 추가
  - [ ] 기존 테스트 코드 변경
- [ ] 커밋 되돌리기
- [ ] 기타

## 해당 PR에 대한 설명
홈화면 UI 개선, 로고 이미지 변경.
Workspace MSW기능 개선
Sidebar 컴포넌트화, 보드에 Navbar, Sidebar 추가.
기존 BoardCard 디렉토리 이름 변경( Workspace 폴더 생성, Box 폴더 생성)
파일로 분리해둔 Router를 이용하여 다시 적용

## 스크린샷
![image](https://user-images.githubusercontent.com/76089508/217509983-ee9465d7-cfd9-49c6-97cf-ff90af65978c.png)
![image](https://user-images.githubusercontent.com/76089508/217511212-260ddd15-ef54-4fa1-8241-480e7171e730.png)

## 기타 정보

2023-02-08 15:34 UTC, whquddnr97 approved these changes
로고 이쁘네용 고생하셨습니다!

2023-02-09 00:28 UTC, JeongGyu98 requested changes
워크스페이스, 보드 데이터를 한번에 받아와서 recoil로 관리하는 방향으로 진행. 
axios 를 한번만 써야 할 것 같네요 .

2023-02-09 00:28 UTC, JeongGyu98 commented on src/interfaces/boardInterface.ts
> +export interface BoardInterface {
워크스페이스 페이지랑 데이터구조 통일해야 할 것 같네요

2023-02-09 00:28 UTC, JeongGyu98 commented on src/pages/Home/index.tsx
> +        axios.get("/boards/one").then((response) => {
워크스페이스, 보드 데이터 통합해서 recoil로 관리해야할 듯 합니다.

2023-02-09 01:19 UTC, vbnm134678 commented on src/pages/Home/index.tsx
> +        axios.get("/boards/one").then((response) => {
추후 pr에서 통합해서 진행하겠습니다!

2023-02-09 01:22 UTC, vbnm134678 commented on src/interfaces/boardInterface.ts
> +export interface BoardInterface {
넵 알겠습니다!

2023-02-09 02:18 UTC, JeongGyu98 approved these changes

2023-02-09 02:19 UTC, merged